version: '3.9'
name: shortener-prod
networks:
  shortener-network:
    external: false

services:
  shortener-prod-app:
    container_name: shortener-prod-app
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:8080
    volumes:
      # - ../:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - shortener-network
    depends_on:
      shortener-prod-db:
        condition: service_healthy

  shortener-prod-db:
    container_name: shortener-prod-db
    image: postgres:15.4
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGUSER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
    expose:
      - 5432
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - shortener-network